In [1]:
import fdcomp
import rasterio
import numpy as np

In [2]:
wd = '/Volumes/Cloud/Yandex/RSCF_Flow_directions/TESTS_raster_generalization'

acc1_src = rasterio.open(f'{wd}/HydroSHEDS/hyd_glo_acc_30s_sa.tif')
acc1 = acc1_src.read(1)
 
dir1_src = rasterio.open(f'{wd}/HydroSHEDS/hyd_glo_dir_30s_sa.tif')
dir1 = dir1_src.read(1)
aff1 = np.array(dir1_src.get_transform())[[1, 2, 0, 4, 5, 3]]

dir2_src = rasterio.open(f'{wd}/COTAT/COTAT_05_flowdir_sa.tif')
dir2 = dir2_src.read(1)
aff2 = np.array(dir2_src.get_transform())[[1, 2, 0, 4, 5, 3]]

aff1

array([ 8.33333333e-03,  0.00000000e+00, -8.50000000e+01,  0.00000000e+00,
       -8.33333333e-03,  1.50000000e+01])

In [3]:
tree, seeds = fdcomp.d8tree(acc1, dir1, aff1)

In [4]:
seeds[0:9]

array([[   3056,     991,    1880,    4070,    4647, 6965746, 5063773],
       [   3511,    3420,    5872,    3177,    3170, 3288084, 3357982],
       [   3789,    2902,    2203,    3163,    2637, 1638512, 2861484],
       [   3718,    4490,    5078,    3165,    2306, 1194040, 2426426],
       [   1372,    1256,     770,    2882,    2452, 1098998, 2678446],
       [   3965,    3830,    2062,    4272,    2315,  919817, 2480874],
       [   1565,    2477,    2177,    3010,    1708,  832793, 1857751],
       [   4194,    4605,    3055,    5831,    2458,  764140, 2635353],
       [   3582,    3660,    1980,    3984,    2114,  605074, 2304509]],
      dtype=uint32)

In [10]:
accuracy = fdcomp.d8comp(dir1, dir2, seeds[0:100])
accuracy * 100

array([8.10200129e+01, 3.15457413e-02, 4.85779295e+01, 7.51517780e+01,
       4.07830343e-02, 4.31965443e-02, 7.81030445e+01, 4.06834825e-02,
       7.75307474e+01, 7.40827024e+01, 7.51219512e+01, 6.72316384e+01,
       4.92610837e-02, 9.00819672e+01, 5.83771162e-02, 5.35331906e-02,
       8.31946755e-02, 7.30569948e+01, 7.10227273e-02, 6.57462196e-02,
       5.66893424e-02, 7.88140162e+01, 8.46740051e-02, 1.43472023e-01,
       1.66427547e+01, 1.50150150e-01, 8.70322019e-02, 6.37393768e+01,
       3.38916256e+01, 1.27877238e-01, 7.53579503e-02, 7.71604938e-02,
       9.99000999e-02, 1.29366106e-01, 9.09090909e-02, 1.03092784e-01,
       7.32064422e-02, 9.31966449e-02, 6.64010624e-02, 7.15137068e-01,
       5.11200000e+01, 5.93810445e+01, 1.34952767e-01, 6.63013699e+01,
       1.62412993e+00, 4.66225166e+01, 6.20020429e+01, 1.53846154e-01,
       8.12000000e+01, 1.02669405e-01, 1.42653352e-01, 1.40252454e-01,
       1.39860140e-01, 1.75131349e-01, 6.17678381e+00, 6.90161527e+00,
      

In [5]:
profile = acc1_src.profile

dst = rasterio.open(f'{wd}/d8tree.tif', 'w', **profile)
dst.write(res, 1)
dst.close()